- type: entity
  id: BaseMagazine.45_ACP
  name: pistol magazine (.45 ACP FMJ)
  parent: [ BaseItem, BaseC1Contraband, RecyclableItemSteelTiny ] # Frontier: BaseSecurityContraband<BaseC1Contraband, added RecyclableItemSteelTiny
  abstract: true
  components:
  - type: Tag
    tags:
      - Magazine.45_ACPFMJ
  - type: BallisticAmmoProvider
    mayTransfer: true
    whitelist:
      tags:
        - Cartridge.45_ACPFMJ
    capacity: 10
  - type: Item
    size: Small
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_pistol_mag.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]
  - type: MagazineVisuals
    magState: mag
    steps: 6
    zeroVisible: false
  - type: Appearance

- type: entity
  id: BaseMagazine.45_ACPHighCapacity
  name: machine pistol magazine (.45 ACP FMJ)
  parent: [BaseItem, BaseC1Contraband, RecyclableItemSteelTiny] # Frontier: added RecyclableItemSteelTiny, BaseC1Contraband
  abstract: true
  components:
  - type: Tag
    tags:
      - Magazine.45_ACPHighCapacity
  - type: BallisticAmmoProvider
    mayTransfer: true
    whitelist:
      tags:
        - Cartridge.45_ACPFMJ
    capacity: 16
  - type: Item
    size: Small
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_pistol_high_capacity_mag.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]
  - type: MagazineVisuals
    magState: mag
    steps: 6
    zeroVisible: false
  - type: Appearance

- type: entity
  id: BaseMagazine.45_ACPSubMachineGun
  name: SMG magazine (.45 ACP FMJ)
  parent: [BaseItem, BaseC1Contraband, RecyclableItemSteelTiny] # Frontier: added RecyclableItemSteelTiny, BaseSecurityContraband<BaseC1Contraband
  abstract: true
  components:
  - type: Tag
    tags:
      - Magazine.45_ACPSubMachineGun
  - type: BallisticAmmoProvider
    mayTransfer: true
    whitelist:
      tags:
        - Cartridge.45_ACPFMJ
    capacity: 35
  - type: Item
    size: Small
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_smg_mag.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]
  - type: MagazineVisuals
    magState: mag
    steps: 6
    zeroVisible: false
  - type: Appearance

- type: entity
  id: Magazine.45_ACPSubMachineGunTopMounted
  name: WT550 magazine (.45 ACP top-mounted)
  parent: [ BaseItem, BaseC1Contraband, RecyclableItemSteelTiny ] # Frontier: BaseSecurityContraband<BaseC1Contraband, added RecyclableItemSteelTiny
  components:
  - type: Tag
    tags:
      - Magazine.45_ACPSubMachineGunTopMounted
  - type: BallisticAmmoProvider
    mayTransfer: true
    proto: Cartridge.45_ACPFMJ
    whitelist:
      tags:
      - Cartridge.45_ACPFMJ
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_smg_mag_top_mounted.rsi
    layers:
      - state: base
        map: ["enum.GunVisualLayers.Base"]
      - state: mag-unshaded-1
        map: ["enum.GunVisualLayers.MagUnshaded"]
        shader: unshaded
  - type: MagazineVisuals
    magState: mag
    steps: 6
    zeroVisible: false
  - type: Appearance
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container

- type: entity
  id: Magazine.45_ACPSubMachineGunTopMountedEmpty
  name: WT550 magazine (.45 ACP top-mounted any)
  parent: Magazine.45_ACPSubMachineGunTopMounted
  components:
  - type: BallisticAmmoProvider
    proto: null

- type: entity
  id: Magazine.45_ACPFMJ
  name: pistol magazine (.45 ACP FMJ)
  parent: BaseMagazine.45_ACP
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPFMJ
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPEmpty
  name: pistol magazine (.45 ACP any)
  suffix: empty
  parent: Magazine.45_ACPFMJ
  components:
  - type: BallisticAmmoProvider
    proto: null
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]


- type: entity
  id: Magazine.45_ACPIncendiary
  name: pistol magazine (.45 ACP incendiary)
  parent: Magazine.45_ACPFMJ
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPIncendiary

- type: entity
  id: Magazine.45_ACPPractice
  name: pistol magazine (.45 ACP practice)
  parent: BaseMagazine.45_ACP
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPPractice
  - type: Sprite
    layers:
    - state: practice
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPUranium
  name: pistol magazine (.45 ACP uranium)
  parent: BaseMagazine.45_ACP
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPUranium
  - type: Sprite
    layers:
    - state: uranium
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPHighCapacityEmpty
  name: machine pistol magazine (.45 ACP any)
  suffix: empty
  parent: BaseMagazine.45_ACPHighCapacity
  components:
  - type: BallisticAmmoProvider
    proto: null
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPHighCapacity
  name: machine pistol magazine (.45 ACP FMJ)
  parent: BaseMagazine.45_ACPHighCapacity
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPFMJ
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPHighCapacityPractice
  name: machine pistol magazine (.45 ACP practice)
  parent: BaseMagazine.45_ACPHighCapacity
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPFMJ
  - type: Sprite
    layers:
    - state: practice
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPSubMachineGun
  name: SMG magazine (.45 ACP FMJ)
  parent: BaseMagazine.45_ACPSubMachineGun
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPFMJ
    whitelist:
      tags:
        - Cartridge.45_ACPFMJ
    soundInsert:
      path: /Audio/Weapons/Guns/MagIn/bullet_insert.ogg
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPSubMachineGunEmpty
  name: SMG magazine (.45 ACP any)
  suffix: empty
  parent: BaseMagazine.45_ACPSubMachineGun
  components:
  - type: BallisticAmmoProvider
    proto: null
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPSubMachineGunPractice
  name: SMG magazine (.45 ACP practice)
  parent: BaseMagazine.45_ACPSubMachineGun
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPPractice
  - type: Sprite
    layers:
    - state: practice
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPSubMachineGunUranium
  name: SMG magazine (.45 ACP uranium)
  parent: BaseMagazine.45_ACPSubMachineGun
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPUranium
  - type: Sprite
    layers:
    - state: uranium
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  parent: BaseMagazine.45_ACPSubMachineGun
  id: Magazine.45_ACPSubMachineGunIncendiary
  name: SMG magazine (.45 ACP incendiary)
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPIncendiary

- type: entity
  id: Magazine.45_ACPRubber
  name: pistol magazine (.45 ACP rubber)
  parent: BaseMagazine.45_ACP
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPRubber
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_pistol_mag.rsi
    layers:
    - state: rubber
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

- type: entity
  id: Magazine.45_ACPSubMachineGunRubber
  name: SMG magazine (.45 ACP rubber)
  parent: BaseMagazine.45_ACPSubMachineGun
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPRubber
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_smg_mag.rsi
    layers:
    - state: rubber
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]


- type: entity
  id: Magazine.45_ACPHighCapacityRubber
  name: machine pistol magazine (.45 ACP rubber)
  parent: BaseMagazine.45_ACPHighCapacity
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPFMJ
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_pistol_high_capacity_mag.rsi
    layers:
    - state: rubber
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]

# Frontier
- type: entity
  id: Magazine.45_ACPSubMachineGunEmp
  name: SMG magazine (.45 ACP emp)
  parent: BaseMagazine.45_ACPSubMachineGun
  components:
  - type: BallisticAmmoProvider
    proto: Cartridge.45_ACPEmp
  - type: Sprite
    sprite: _Mono/Objects/Weapons/Guns/Ammunition/Magazine/.45_ACP/.45_ACP_smg_mag.rsi
    layers:
    - state: emp
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-1
      map: ["enum.GunVisualLayers.Mag"]
