// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 gluesniffler <linebarrelerenthusiast@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.GameTicking.Managers;
using Content.Client.Light;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Shitcode.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StatusTabControl : BaseTabControl
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    private ClientGameTicker? _gameTicker;
    private LightCycleSystem? _lightCycle;

    public StatusTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs e)
    {
        if (_gameTicker != null)
        {
            if (_lightCycle != null && _lightCycle.TryGetCycleProgress(out var progress))
            {
                const int minutesPerDay = 24 * 60;
                var totalMinutes = (int) (progress * minutesPerDay) % minutesPerDay;
                var hours = totalMinutes / 60;
                var minutes = totalMinutes % 60;

                StationTime.Text = Loc.GetString(
                    "lobby-state-player-status-planet-time",
                    ("time", $"{hours:00}:{minutes:00}"));
                return;
            }

            var roundTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }

        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");
    }

    public override bool UpdateState()
    {
        // Goob's PR added ClientGameTicker.InGameInfoBlob and InGameInfoBlobUpdated.
        // Cataclysm14 does not have those members yet, so keep the status tab compiling
        // and still update round time using the existing RoundStartTimeSpan field.
        _gameTicker ??= _entManager.System<ClientGameTicker>();
        _lightCycle ??= _entManager.System<LightCycleSystem>();
        return true;
    }

    private void UpdateInfoBlob()
    {
        // Intentionally left blank for Cataclysm14 compatibility.
        // Port TickerInGameInfoEvent/InGameInfoBlob later to populate ServerInfo.
    }

    protected override void Resized()
    {
    }
}
