using System.Linq;
using Content.Client._Cataclysm14.UserInterface.Controls;
using Content.Client._Shitmed.UserInterface.Systems.Targeting;
using Content.Client.Alerts;
using Content.Client.GameTicking.Managers;
using Content.Shared.Damage.Components;
using Content.Shared._Shitmed.Targeting;
using Content.Shared.Alert;
using Content.Shared.Damage;
using Content.Shared.FixedPoint;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Nutrition.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Cataclysm14.UserInterface.Systems;

[GenerateTypedNameReferences]
public sealed partial class CataclysmSidebar : UIWidget
{
    private readonly IPlayerManager _playerManager;
    private readonly IEntityManager _ent;
    private readonly IEntitySystemManager _entitySystem = default!;
    private readonly TargetingUIController _targetingController;
    //private readonly ClientGameTicker _gameTicker;

    private readonly EntityQuery<DamageableComponent> _damageableQuery;
    private readonly EntityQuery<MobThresholdsComponent> _mobThresholdsQuery;
    private readonly EntityQuery<ThirstComponent> _thirstQuery;
    private readonly EntityQuery<HungerComponent> _hungerQuery;
    private readonly EntityQuery<StaminaComponent> _staminaQuery;

    private EntityUid? _cachedPlayer = null;
    private DamageableComponent? _cachedDamageable = null;
    private MobThresholdsComponent? _cachedMobThresholds = null;
    private ThirstComponent? _cachedThirst = null;
    private HungerComponent? _cachedHunger = null;
    private StaminaComponent? _cachedStamina = null;

    // todo: remove that shit and change only with events
    private TimeSpan _cachedTime = TimeSpan.Zero;
    private FixedPoint2 _cachedHpLevel = FixedPoint2.New(9999);
    private ThirstThreshold _cachedThirstThreshold = (ThirstThreshold)(1 << 7);
    private HungerThreshold _cachedHungerThreshold = (HungerThreshold)(1 << 7);

    private Dictionary<TargetBodyPart, (Label graph, Label labels, Button dollButton)> _bodyPartToLabel;
    private readonly Dictionary<AlertKey, CataAlertControl> _alertControls = new();

    private FixedPoint2 _deadThreshold = FixedPoint2.New(200);

    public event EventHandler<ProtoId<AlertPrototype>>? AlertPressed;

    public CataclysmSidebar()
    {
        RobustXamlLoader.Load(this);
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        _ent = IoCManager.Resolve<IEntityManager>();
        //_gameTiming = IoCManager.Resolve<GameTiming>(); crash bruh because too early
        _entitySystem = IoCManager.Resolve<IEntitySystemManager>();
        _targetingController = UserInterfaceManager.GetUIController<TargetingUIController>();

        //_gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>(); crash bruh because too early

        _damageableQuery = _ent.GetEntityQuery<DamageableComponent>();
        _mobThresholdsQuery = _ent.GetEntityQuery<MobThresholdsComponent>();
        _thirstQuery = _ent.GetEntityQuery<ThirstComponent>();
        _hungerQuery = _ent.GetEntityQuery<HungerComponent>();
        _staminaQuery = _ent.GetEntityQuery<StaminaComponent>();

        // hardshitcode area
        StatusHead.Text = "     ###\n     ###";
        StatusTorso.Text = " ##### \n#######\n#######\n ##### ";
        StatusGroin.Text = " ##### ";
        StatusLArm.Text = "\n  #\n  #\n ##\n # ";
        StatusRArm.Text = "\n#  \n#  \n## \n # ";
        StatusLHand.Text = "#  \n\n\n\n"; // holy \n
        StatusRHand.Text = "  #\n\n\n\n";
        StatusLLeg.Text = "### \n### \n### \n ## \n ## ";
        StatusRLeg.Text = "###\n###\n###\n## \n## ";
        StatusLFoot.Text = "     # ";
        StatusRFoot.Text = "#";

        TargetDollHead.Text = StatusHead.Text;
        TargetDollTorso.Text = StatusTorso.Text;
        TargetDollGroin.Text = StatusGroin.Text;
        TargetDollLArm.Text = StatusLArm.Text;
        TargetDollRArm.Text = StatusRArm.Text;
        TargetDollLHand.Text = StatusLHand.Text;
        TargetDollRHand.Text = StatusRHand.Text;
        TargetDollLLeg.Text = StatusLLeg.Text;
        TargetDollRLeg.Text = StatusRLeg.Text;
        TargetDollLFoot.Text = StatusLFoot.Text;
        TargetDollRFoot.Text = StatusRFoot.Text;

        _bodyPartToLabel = new()
        {
            { TargetBodyPart.Head, (StatusHead, StatusHeadLabel, TargetDollHead) },
            { TargetBodyPart.Torso, (StatusTorso, StatusTorsoLabel, TargetDollTorso) },
            { TargetBodyPart.Groin, (StatusGroin, StatusGroinLabel, TargetDollGroin) },
            { TargetBodyPart.LeftArm, (StatusLArm, StatusLArmLabel, TargetDollLArm) },
            { TargetBodyPart.LeftHand, (StatusLHand, StatusLHandLabel, TargetDollLHand) },
            { TargetBodyPart.RightArm, (StatusRArm, StatusRArmLabel, TargetDollRArm) },
            { TargetBodyPart.RightHand, (StatusRHand, StatusRHandLabel, TargetDollRHand) },
            { TargetBodyPart.LeftLeg, (StatusLLeg, StatusLLegLabel, TargetDollLLeg) },
            { TargetBodyPart.LeftFoot, (StatusLFoot, StatusLFootLabel, TargetDollLFoot) },
            { TargetBodyPart.RightLeg, (StatusRLeg, StatusRLegLabel, TargetDollRLeg) },
            { TargetBodyPart.RightFoot, (StatusRFoot, StatusRFootLabel, TargetDollRFoot) }
        };

        foreach (var (part , (_, _, bodyPartButton)) in _bodyPartToLabel)
        {
            bodyPartButton.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.OnPressed += _ => SetActiveBodyPart(part);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args) // sorry, mr. FPS
    {
        base.FrameUpdate(args);

        var u = _playerManager.LocalEntity;
        if (u == null)
        {
            HealthContainer.Visible = false;
            return;
        }

        //var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan); // from PdaMenu
        /*var stationTime = _gameTicker.RoundDuration();
        if (stationTime != _cachedTime)
        {
            _cachedTime = stationTime;
            TimeLabel.Text = stationTime.ToString("hh\\:mm\\:ss");
        } */

        if (u != _cachedPlayer)
        {
            _cachedPlayer = u;
            _damageableQuery.TryComp(u, out _cachedDamageable);
            _mobThresholdsQuery.TryComp(u, out _cachedMobThresholds);
            _thirstQuery.TryComp(u, out _cachedThirst);
            _hungerQuery.TryComp(u, out _cachedHunger);
            _staminaQuery.TryComp(u, out _cachedStamina);

            var dead = _cachedMobThresholds?.Thresholds.FirstOrDefault(t => t.Value == MobState.Dead).Key;
            if (dead is {} deady) // fck c# why i cant just == null
                _deadThreshold = deady;

            Root?.InvalidateMeasure(); // queue layout fix
        }

        if (_cachedDamageable == null || _cachedMobThresholds == null)
        {
            if (HealthContainer.Visible)
            {
                HealthContainer.Visible = false;
            }
            // else skip render
        }
        else
        {
            if (!HealthContainer.Visible)
            {
                HealthContainer.Visible = true;
            }

            // 1.0f -> 100, so 9% = 9, 18% = 18, etc.
            var hpLevel = (_cachedDamageable.Damage.GetTotal() / _deadThreshold).Value;

            if (_cachedHpLevel != hpLevel)
            {
                _cachedHpLevel = hpLevel;
                hpLevel = hpLevel*2;
                var (healthValue, healthColor) = hpLevel switch
                {
                    < 9 => ("|||||", new Color(0, 110, 0)),
                    < 18 => ("||||\\", new Color(0, 110, 0)),
                    < 27 => ("||||.", new Color(0, 110, 0)), // dark green, thx paint
                    < 36 => ("|||\\.", Color.Green),
                    < 45 => ("|||..", Color.Green),
                    < 54 => ("||\\..", Color.Yellow),
                    < 63 => ("||...", Color.Yellow),
                    < 72 => ("|\\...", new Color(255, 150, 150)),
                    < 81 => ("|....", new Color(255, 150, 150)), // pink
                    < 90 => ("\\....", Color.Red),
                    < 99 => (".....", Color.Red),
                    < 109 => ("|||||", Color.Red),
                    < 118 => ("||||\\", Color.Red),
                    < 127 => ("||||.", Color.Red),
                    < 136 => ("|||\\.", Color.Red),
                    < 145 => ("|||..", Color.Red),
                    < 154 => ("||\\..", Color.Red),
                    < 163 => ("||...", Color.Red),
                    < 172 => ("|\\...", Color.Red),
                    < 181 => ("|....", Color.Red),
                    < 190 => ("\\....", Color.Red),
                    >= 190 => (".....", Color.Red),
                };

                HealthLabel.Text = healthValue;
                HealthLabel.Modulate = healthColor;
            }
        }

        if (_cachedThirst == null)
        {
            if (ThirstContainer.Visible)
            {
                ThirstContainer.Visible = false;
            }
        }
        else
        {
            if (!ThirstContainer.Visible)
            {
                ThirstContainer.Visible = true;
            }

            var thirst = _cachedThirst.CurrentThirstThreshold;
            if (_cachedThirstThreshold != thirst)
            {
                _cachedThirstThreshold = thirst;
                var (value, color) = thirst switch
                {
                    ThirstThreshold.Dead => ("Dead", Color.Red),
                    ThirstThreshold.Parched => ("Parched", Color.Red),
                    ThirstThreshold.Thirsty => ("Thirsty", Color.Yellow),
                    ThirstThreshold.Okay => ("Okay", Color.Green),
                    ThirstThreshold.OverHydrated => ("Over hydrated", new Color(0, 110, 0)), // dark green
                    _ => ("Unknown", Color.Gray)
                };

                ThirstLabel.Text = value;
                ThirstLabel.Modulate = color;
            }
        }

        if (_cachedHunger == null)
        {
            if (HungerContainer.Visible)
            {
                HungerContainer.Visible = false;
            }
        }
        else
        {
            if (!HungerContainer.Visible)
            {
                HungerContainer.Visible = true;
            }

            var hunger = _cachedHunger.CurrentThreshold;
            if (_cachedHungerThreshold != hunger)
            {
                _cachedHungerThreshold = hunger;
                var (value, color) = hunger switch
                {
                    HungerThreshold.Dead => ("Dead", Color.Red),
                    HungerThreshold.Starving => ("Starving", Color.Red),
                    HungerThreshold.Peckish => ("Peckish", Color.Yellow),
                    HungerThreshold.Okay => ("Okay", Color.Green),
                    HungerThreshold.Overfed => ("Overfed", new Color(0, 110, 0)), // dark green
                    _ => ("Unknown", Color.Gray)
                };

                HungerLabel.Text = value;
                HungerLabel.Modulate = color;
            }
        }

        if (_cachedStamina == null)
        {
            if (StaminaContainer.Visible)
            {
                StaminaContainer.Visible = false;
            }
        }
        else
        {
            if (!StaminaContainer.Visible)
            {
                StaminaContainer.Visible = true;
            }
            // 1.0f -> 100, so 9% = 9, 18% = 18, etc.
            //yes this is hardcoded for 100 stamina :godo:
            var (staminaValue, staminaColor) = _cachedStamina.StaminaDamage switch
            {
                < 9 => ("|||||", new Color(0, 110, 0)),
                < 18 => ("||||\\", new Color(0, 110, 0)),
                < 27 => ("||||.", new Color(0, 110, 0)), // dark green, thx paint
                < 36 => ("|||\\.", Color.Green),
                < 45 => ("|||..", Color.Green),
                < 54 => ("||\\..", Color.Yellow),
                < 63 => ("||...", Color.Yellow),
                < 72 => ("|\\...", new Color(255, 150, 150)),
                < 81 => ("|....", new Color(255, 150, 150)), // pink
                < 90 => ("\\....", Color.Red),
                >= 90 => (".....", Color.Red),
            };
            StaminaLabel.Text = staminaValue;
            StaminaLabel.Modulate = staminaColor;
        }
    }

    private void CheckEmptyContainers()
    {
        if (!HealthStatusContainer.Visible && !TargetDollContainer.Visible)
        {
            HealthAndDollContainer.Visible = false;
            HealthLabelName.Text = "General Health     : ";
        }
        else
        {
            HealthAndDollContainer.Visible = true;
            HealthLabelName.Text = "General Health      : ";
        }

        Root?.InvalidateMeasure();
    }

    public void SetVisibleStatusDoll(bool visible)
    {
        HealthStatusContainer.Visible = visible;
        HealthStatusLabelsContainer.Visible = visible;
        CheckEmptyContainers();
    }

    public void SetStatusDoll(Dictionary<TargetBodyPart, TargetIntegrity> state)
    {
        foreach (var (bodyPart, integrity) in state)
        {
            var (color, text) = integrity switch
            {
                TargetIntegrity.Healthy => (new Color(0, 110, 0), "|||||"),
                TargetIntegrity.LightlyWounded => (Color.Green, "||||."),
                TargetIntegrity.SomewhatWounded => (Color.Yellow, "|||.."),
                TargetIntegrity.ModeratelyWounded => (Color.Yellow, "||..."),
                TargetIntegrity.HeavilyWounded => (new Color(255, 150, 150), "|\\..."),
                TargetIntegrity.CriticallyWounded => (new Color(255, 150, 150), "|...."),
                TargetIntegrity.Severed => (Color.Red, "/....."),
                TargetIntegrity.Dead => (Color.Red, "....."),
                TargetIntegrity.Disabled => (Color.Gray, "....."),
                _ => (Color.Black, "....."), // oops
            };
            var (graph, label, _) = _bodyPartToLabel[bodyPart];
            graph.Modulate = color;
            label.Modulate = color;
            label.Text = text;
        }
    }

    private void SetActiveBodyPart(TargetBodyPart bodyPart) => _targetingController.CycleTarget(bodyPart);

    public void SetBodyPartsVisible(TargetBodyPart bodyPart)
    {
        foreach (var (part, (_, _, dollButton)) in _bodyPartToLabel)
        {
            dollButton.Pressed = part == bodyPart;
        }
    }

    public void SetTargetDollVisible(bool visible)
    {
        TargetDollContainer.Visible = visible;
        TargetDollLabelContainer.Visible = visible;
        CheckEmptyContainers();
    }

    private CataAlertControl CreateAlertControl(AlertPrototype alert, AlertState alertState)
    {
        (TimeSpan, TimeSpan)? cooldown = null;
        if (alertState.ShowCooldown)
            cooldown = alertState.Cooldown;

        var alertControl = new CataAlertControl(alert, alertState.Severity)
        {
            Cooldown = cooldown
        };

        alertControl.OnPressed += AlertControlPressed;
        return alertControl;
    }

    private void AlertControlPressed(BaseButton.ButtonEventArgs args)
    {
        if (args.Button is not CataAlertControl control)
            return;

        if (args.Event.Function != EngineKeyFunctions.UIClick)
            return;

        AlertPressed?.Invoke(this, control.Alert.ID);
    }

    public void ClearAllAlerts()
    {
        foreach (var alertControl in _alertControls.Values)
        {
            alertControl.OnPressed -= AlertControlPressed;
            alertControl.Dispose();
        }

        _alertControls.Clear();
    }

    // from AlertsUI.xaml.cs
    public void SyncAlert(ClientAlertsSystem alertsSystem, AlertOrderPrototype? alertOrderPrototype, IReadOnlyDictionary<AlertKey, AlertState> alertStates)
    {
        // remove any controls with keys no longer present
        if (SyncRemoveControls(alertStates))
            return;

        // now we know that alertControls contains alerts that should still exist but
        // may need to updated,
        // also there may be some new alerts we need to show.
        // further, we need to ensure they are ordered w.r.t their configured order
        SyncUpdateControls(alertsSystem, alertOrderPrototype, alertStates);
    }

    private bool SyncRemoveControls(IReadOnlyDictionary<AlertKey, AlertState> alertStates)
    {
        var toRemove = new List<AlertKey>();
        foreach (var existingKey in _alertControls.Keys)
        {
            if (!alertStates.ContainsKey(existingKey))
                toRemove.Add(existingKey);
        }

        foreach (var alertKeyToRemove in toRemove)
        {
            _alertControls.Remove(alertKeyToRemove, out var control);
            if (control == null)
                return true;
            AlertsContainer.Children.Remove(control);
        }

        return false;
    }

    private void SyncUpdateControls(AlertsSystem alertsSystem, AlertOrderPrototype? alertOrderPrototype,
        IReadOnlyDictionary<AlertKey, AlertState> alertStates)
    {
        foreach (var (alertKey, alertState) in alertStates)
        {
            if (!alertKey.AlertType.HasValue)
            {
                //Logger.WarningS("alert", "found alertkey without alerttype," +
                //                         " alert keys should never be stored without an alerttype set: {0}", alertKey);
                continue;
            }

            var alertType = alertKey.AlertType.Value;
            if (!alertsSystem.TryGet(alertType, out var newAlert))
            {
                //Logger.ErrorS("alert", "Unrecognized alertType {0}", alertType);
                continue;
            }

            if (_alertControls.TryGetValue(newAlert.AlertKey, out var existingAlertControl) &&
                existingAlertControl.Alert.ID == newAlert.ID)
            {
                // key is the same, simply update the existing control severity / cooldown
                existingAlertControl.SetSeverity(alertState.Severity);
                if (alertState.ShowCooldown)
                    existingAlertControl.Cooldown = alertState.Cooldown;
            }
            else
            {
                if (existingAlertControl != null)
                    AlertsContainer.Children.Remove(existingAlertControl);

                if (!newAlert.VisibleInCataclysmSideBar)
                    continue;

                // this is a new alert + alert key or just a different alert with the same
                // key, create the control and add it in the appropriate order
                var newAlertControl = CreateAlertControl(newAlert, alertState);

                //TODO: Can the presenter sort the states before giving it to us?
                if (alertOrderPrototype != null)
                {
                    var added = false;
                    foreach (var alertControl in AlertsContainer.Children)
                    {
                        if (alertOrderPrototype.Compare(newAlert, ((CataAlertControl) alertControl).Alert) >= 0)
                            continue;

                        var idx = alertControl.GetPositionInParent();
                        AlertsContainer.Children.Add(newAlertControl);
                        newAlertControl.SetPositionInParent(idx);
                        added = true;
                        break;
                    }

                    if (!added)
                        AlertsContainer.Children.Add(newAlertControl);
                }
                else
                {
                    AlertsContainer.Children.Add(newAlertControl);
                }

                _alertControls[newAlert.AlertKey] = newAlertControl;
            }
        }
    }
    // end AlertsUI.xaml.cs ctrl+c ctrl+v
}

