#You need to add "Job" in front of the roleLoadout ID of the job/profession you wanna add loadout to lol.
- type: roleLoadout
  id: JobProfessionUnemployed
  groups:
  #Pants
  - LoadoutGroupPants
  - LoadoutGroupShoes
  - LoadoutGroupEyewear
  - LoadoutGroupHat
  - LoadoutGroupShirt

- type: roleLoadout
  id: JobProfessionPriest
  groups:
  - LoadoutGroupPants
  - LoadoutGroupShoes
  - LoadoutGroupPriestEyewear
  - LoadoutGroupPriestHat
  - LoadoutGroupPriestShirt
  - LoadoutGroupPriestGear
  - LoadoutGroupPriestAccessories

- type: roleLoadout
  id: JobProfessionPoliceOfficer
  groups:
  - LoadoutGroupPoliceOfficerUniform
  - LoadoutGroupPoliceOfficerVest
  - LoadoutGroupPoliceOfficerFaceCovering
