#MARK: US Citizen
- type: job
  id: JobCitizenUS
  name: job-name-citizen-US
  description: job-description-citizen-US
  playTimeTracker: JobTimeTrackerCitizenUS
  # setPreference: false # Frontier
  # requirements:
  #   - !type:OverallPlaytimeRequirement
  #     time: 10800
  # startingGear: CargoTechGear
  icon: "JobIconCitizenUS"
  # supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # special:
  # - !type:GiveItemOnHolidaySpecial
  #   holiday: BoxingDay
  #   prototype: BoxCardboard

- type: playTimeTracker
  id: JobTimeTrackerCitizenUS
