using Content.Shared.Actions;
using Robust.Shared.GameObjects;
using Robust.Shared.Serialization;

namespace Content.Shared._Cataclysm14.Zombies.Smoker;

public sealed partial class SmokerTongueActionEvent : EntityTargetActionEvent
{
}

/// <summary>
/// Client --> Server request generated by the on-screen escape button
/// </summary>
[Serializable, NetSerializable]
public sealed class SmokerStruggleRequestEvent : EntityEventArgs
{
}

/// <summary>
/// Client --> Server notification that a Smoker tongue action entered targeting mode
/// This is deliberately separate from actually firing the action
/// </summary>
[Serializable, NetSerializable]
public sealed class SmokerTongueArmRequestEvent(NetEntity action) : EntityEventArgs
{
    public NetEntity Action = action;
}

/// <summary>
/// Client --> Server notification that a Smoker tongue action was cancelled after its arm lock expired
/// No sound is played for this event
/// </summary>
[Serializable, NetSerializable]
public sealed class SmokerTongueDisarmRequestEvent(NetEntity action) : EntityEventArgs
{
    public NetEntity Action = action;
}

/// <summary>
/// Client --> Server request to release the currently hooked victim
/// This is allowed even while the tongue action itself is on it's normal cooldown
/// </summary>
[Serializable, NetSerializable]
public sealed class SmokerTongueCancelRequestEvent(NetEntity action) : EntityEventArgs
{
    public NetEntity Action = action;
}
