- type: loadoutGroup
  id: LoadoutGroupShoes
  name: loadout-group-shoes
  loadouts:
  #MARK: Sneakers
  - LoadoutEntryClothingShoesSneakersWhite
  - LoadoutEntryClothingShoesSneakersRed
  - LoadoutEntryClothingShoesSneakersBlue
  - LoadoutEntryClothingShoesSneakersGreen
  - LoadoutEntryClothingShoesSneakersYellow
  - LoadoutEntryClothingShoesSneakersPurple
  - LoadoutEntryClothingShoesSneakersBlack
  #MARK: Workboots
  - LoadoutEntryClothingShoesBootsWorkbootsTan
  - LoadoutEntryClothingShoesBootsWorkbootsOlive
  - LoadoutEntryClothingShoesBootsWorkbootsBlack
  - LoadoutEntryClothingShoesBootsWorkbootsRangerGreen
  - LoadoutEntryClothingShoesBootsWorkbootsCoyoteBrown
  - LoadoutEntryClothingShoesBootsWorkbootsWhite
  #MARK: Laceup Shoes
  - LoadoutEntryClothingShoesBootsLaceup
  #MARK: Unlocks
  - LoadoutEntryClothingShoesReebokAlienStompers
  fallbacks:
  - LoadoutEntryClothingShoesSneakersBlack

#MARK: Sneakers
- type: loadout
  id: LoadoutEntryClothingShoesSneakersWhite
  equipment:
    shoes: ClothingShoesSneakersWhite

- type: loadout
  id: LoadoutEntryClothingShoesSneakersRed
  equipment:
    shoes: ClothingShoesSneakersRed

- type: loadout
  id: LoadoutEntryClothingShoesSneakersBlue
  equipment:
    shoes: ClothingShoesSneakersBlue

- type: loadout
  id: LoadoutEntryClothingShoesSneakersGreen
  equipment:
    shoes: ClothingShoesSneakersGreen

- type: loadout
  id: LoadoutEntryClothingShoesSneakersYellow
  equipment:
    shoes: ClothingShoesSneakersYellow

- type: loadout
  id: LoadoutEntryClothingShoesSneakersPurple
  equipment:
    shoes: ClothingShoesSneakersPurple

- type: loadout
  id: LoadoutEntryClothingShoesSneakersBlack
  equipment:
    shoes: ClothingShoesSneakersBlack

#MARK: Workboots
- type: loadout
  id: LoadoutEntryClothingShoesBootsWorkbootsTan
  equipment:
    shoes: ClothingShoesBootsWorkbootsTan

- type: loadout
  id: LoadoutEntryClothingShoesBootsWorkbootsOlive
  equipment:
    shoes: ClothingShoesBootsWorkbootsOlive

- type: loadout
  id: LoadoutEntryClothingShoesBootsWorkbootsBlack
  equipment:
    shoes: ClothingShoesBootsWorkbootsBlack

- type: loadout
  id: LoadoutEntryClothingShoesBootsWorkbootsRangerGreen
  equipment:
    shoes: ClothingShoesBootsWorkbootsRangerGreen

- type: loadout
  id: LoadoutEntryClothingShoesBootsWorkbootsCoyoteBrown
  equipment:
    shoes: ClothingShoesBootsWorkbootsCoyoteBrown

- type: loadout
  id: LoadoutEntryClothingShoesBootsWorkbootsWhite
  equipment:
    shoes: ClothingShoesBootsWorkbootsWhite

#MARK: Laceup Shoes
- type: loadout
  id: LoadoutEntryClothingShoesBootsLaceup
  equipment:
    shoes: ClothingShoesBootsLaceup

#MARK: Reebok Alien Stompers
- type: loadout
  id: LoadoutEntryClothingShoesReebokAlienStompers
  effects:
  - !type:GroupLoadoutEffect
    proto: ReebokAlienStompersTimer
  equipment:
    shoes: ClothingShoesReebokAlienStompers

#MARK: Unlocks
- type: loadoutEffectGroup
  id: ReebokAlienStompersTimer
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours
