- type: loadoutGroup
  id: LoadoutGroupHat
  name: loadout-group-hat
  loadouts:
  #MARK: Cap
  - LoadoutEntryClothingHeadHatCapBaseballWhite
  - LoadoutEntryClothingHeadHatCapBaseballRed
  - LoadoutEntryClothingHeadHatCapBaseballBlue
  - LoadoutEntryClothingHeadHatCapBaseballGreen
  - LoadoutEntryClothingHeadHatCapBaseballYellow
  - LoadoutEntryClothingHeadHatCapBaseballPurple
  - LoadoutEntryClothingHeadHatCapBaseballBlack
  - LoadoutEntryClothingHeadHatCapBaseballBeige
  - LoadoutEntryClothingHeadHatCapBaseballBrown
  - LoadoutEntryClothingHeadHatCapBaseballOlive
  - LoadoutEntryClothingHeadHatCapBaseballRangerGreen
  #MARK: Beanie
  - LoadoutEntryClothingHeadHatBeanieBlack
  - LoadoutEntryClothingHeadHatBeanieBeige
  - LoadoutEntryClothingHeadHatBeaniePurple
  - LoadoutEntryClothingHeadHatBeanieGray
  - LoadoutEntryClothingHeadHatBeanieTan
  - LoadoutEntryClothingHeadHatBeanieOlive
  - LoadoutEntryClothingHeadHatBeanieRangerGreen
  fallbacks:
  - LoadoutEntryClothingHeadHatBeanieBlack

#MARK: Caps
- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballWhite
  equipment:
    head: ClothingHeadHatCapBaseballWhite

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballRed
  equipment:
    head: ClothingHeadHatCapBaseballRed

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballBlue
  equipment:
    head: ClothingHeadHatCapBaseballBlue

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballGreen
  equipment:
    head: ClothingHeadHatCapBaseballGreen

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballYellow
  equipment:
    head: ClothingHeadHatCapBaseballYellow

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballPurple
  equipment:
    head: ClothingHeadHatCapBaseballPurple

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballBlack
  equipment:
    head: ClothingHeadHatCapBaseballBlack

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballBeige
  equipment:
    head: ClothingHeadHatCapBaseballBeige

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballBrown
  equipment:
    head: ClothingHeadHatCapBaseballBrown

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballOlive
  equipment:
    head: ClothingHeadHatCapBaseballOlive

- type: loadout
  id: LoadoutEntryClothingHeadHatCapBaseballRangerGreen
  equipment:
    head: ClothingHeadHatCapBaseballRangerGreen

#MARK: Beanie
- type: loadout
  id: LoadoutEntryClothingHeadHatBeanieBlack
  equipment:
    head: ClothingHeadHatBeanieBlack

- type: loadout
  id: LoadoutEntryClothingHeadHatBeanieBeige
  equipment:
    head: ClothingHeadHatBeanieBeige

- type: loadout
  id: LoadoutEntryClothingHeadHatBeaniePurple
  equipment:
    head: ClothingHeadHatBeaniePurple

- type: loadout
  id: LoadoutEntryClothingHeadHatBeanieGray
  equipment:
    head: ClothingHeadHatBeanieGray

- type: loadout
  id: LoadoutEntryClothingHeadHatBeanieTan
  equipment:
    head: ClothingHeadHatBeanieTan

- type: loadout
  id: LoadoutEntryClothingHeadHatBeanieOlive
  equipment:
    head: ClothingHeadHatBeanieOlive

- type: loadout
  id: LoadoutEntryClothingHeadHatBeanieRangerGreen
  equipment:
    head: ClothingHeadHatBeanieRangerGreen
